conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/cifar10/cifar_test/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 7
    intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.05
