conditioning:
  method: ps
  params:
    scale: 0.1

data:
  name: ffhq
  root: ./data/cifar10/cifar_test/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [16, 17]  # for box
    #mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 32
    margin: !!python/tuple [2, 2] # for box/ different resolution


  noise:
    name: gaussian
    sigma: 0.05

