conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/cifar10/cifar_test/

measurement:
  operator:
    name: nonlinear_blur
    #opt_yml_path: ./bkse/options/generate_blur/default.yml
    opt_yml_path: ./configs/default.yml
  noise: 
    name: gaussian
    sigma: 0.05
