conditioning:
  method: ps
  params:
    scale: 1.0

data:
  name: ffhq
  root: ./data/cifar10/cifar_test/

measurement:
  operator:
    name: phase_retrieval
    oversample: 2.0

  noise: 
    name: gaussian
    sigma: 0.05
