conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/cifar10/cifar_test/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 32, 32]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.05
